//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Candidat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcialEntities1 : DbContext
    {
        public AcialEntities1()
            : base("name=AcialEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidat> Candidat { get; set; }
        public virtual DbSet<EvenementCandidat> EvenementCandidat { get; set; }
        public virtual DbSet<FavorisCandidat> FavorisCandidat { get; set; }
        public virtual DbSet<FichierCandidat> FichierCandidat { get; set; }
        public virtual DbSet<Humain> Humain { get; set; }
        public virtual DbSet<IDENTIFIANTSALARIE> IDENTIFIANTSALARIE { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Salarie> Salarie { get; set; }
        public virtual DbSet<TacheCandidat> TacheCandidat { get; set; }
        public virtual DbSet<typActionCandidat> typActionCandidat { get; set; }
        public virtual DbSet<typEvenementCandidat> typEvenementCandidat { get; set; }
        public virtual DbSet<typFichierCandidat> typFichierCandidat { get; set; }
        public virtual DbSet<typOrigineCandidat> typOrigineCandidat { get; set; }
        public virtual DbSet<typPrioriteCandidat> typPrioriteCandidat { get; set; }
        public virtual DbSet<typStatutCandidat> typStatutCandidat { get; set; }
        public virtual DbSet<typTdb> typTdb { get; set; }
    }
}
