//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Candidat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidat()
        {
            this.EvenementCandidat = new HashSet<EvenementCandidat>();
            this.FavorisCandidat = new HashSet<FavorisCandidat>();
            this.FichierCandidat = new HashSet<FichierCandidat>();
            this.TacheCandidat = new HashSet<TacheCandidat>();
        }
    
        public int CdCandidat { get; set; }
        public int CdHumain { get; set; }
        public Nullable<System.DateTime> DtDisponibilite { get; set; }
        public string LbDisponibilite { get; set; }
        public string Remuneration { get; set; }
        public string Mobilite { get; set; }
        public Nullable<int> TypAction { get; set; }
        public Nullable<int> TypPriorite { get; set; }
        public Nullable<int> TypOrigine { get; set; }
        public Nullable<int> TypStatut { get; set; }
        public Nullable<bool> InfCom { get; set; }
        public string MCEntreprise { get; set; }
        public string MCFonctionnel { get; set; }
        public string MCTechnique { get; set; }
        public Nullable<System.DateTime> DtCreation { get; set; }
        public string CreePar { get; set; }
        public Nullable<System.DateTime> DtModification { get; set; }
        public string ModifiePar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvenementCandidat> EvenementCandidat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavorisCandidat> FavorisCandidat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FichierCandidat> FichierCandidat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TacheCandidat> TacheCandidat { get; set; }
        public virtual Humain Humain { get; set; }
        public virtual Salarie Salarie { get; set; }
        public virtual Salarie Salarie1 { get; set; }
        public virtual typActionCandidat typActionCandidat { get; set; }
        public virtual typOrigineCandidat typOrigineCandidat { get; set; }
        public virtual typPrioriteCandidat typPrioriteCandidat { get; set; }
        public virtual typStatutCandidat typStatutCandidat { get; set; }
    }
}
