//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Candidat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavorisCandidat
    {
        public int CdFavoris { get; set; }
        public int CdCandidat { get; set; }
        public string CdSalarie { get; set; }
    
        public virtual Candidat Candidat { get; set; }
        public virtual Salarie Salarie { get; set; }
    }
}
