//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Candidat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichierCandidat
    {
        public int CdFichier { get; set; }
        public int CdCandidat { get; set; }
        public int TypFichier { get; set; }
        public string Nom { get; set; }
        public string LienPath { get; set; }
        public System.DateTime DtCreation { get; set; }
        public System.DateTime DtModification { get; set; }
    
        public virtual Candidat Candidat { get; set; }
        public virtual typFichierCandidat typFichierCandidat { get; set; }
    }
}
