//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Candidat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDENTIFIANTSALARIE
    {
        public int cdId { get; set; }
        public string cdSalarie { get; set; }
        public string key { get; set; }
        public System.DateTime DtCreation { get; set; }
        public System.DateTime DtModification { get; set; }
    
        public virtual Salarie Salarie { get; set; }
    }
}
