//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Candidat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacheCandidat
    {
        public int CdTache { get; set; }
        public int CdCandidat { get; set; }
        public string CdCreateur { get; set; }
        public string CdReceveur { get; set; }
        public Nullable<System.DateTime> DtAction { get; set; }
        public System.DateTime DtEnvoi { get; set; }
        public bool Statut { get; set; }
    
        public virtual Candidat Candidat { get; set; }
        public virtual Salarie Salarie { get; set; }
        public virtual Salarie Salarie1 { get; set; }
    }
}
