//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Candidat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TacheCandidat
    {
        public int CdTache { get; set; }
        public int CdCandidat { get; set; }
        [Display(Name = "Créée par")]
        public string CdCreateur { get; set; }
        [Display(Name = "Reçue par")]
        public string CdReceveur { get; set; }
        [Display(Name = "Pour le")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> DtAction { get; set; }
        [Display(Name = "Le")]
        public System.DateTime DtEnvoi { get; set; }
        [Display(Name = "Faite")]
        public bool Statut { get; set; }
        [Display(Name = "Détails")]
        public string Details { get; set; }

        public virtual Candidat Candidat { get; set; }
        public virtual Salarie Salarie { get; set; }
        public virtual Salarie Salarie1 { get; set; }
    }
}
